name: Bug report
description: Report an issue or bug with this application
labels: ['bug']
body:
  - type: textarea
    id: bug-report
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true

  - type: textarea
    id: repro-steps
    attributes:
      label: To Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true

  - type: textarea
    id: code-snippets
    attributes:
      label: Code Snippets
      description: Paste any relevant code snippet that helps us reproduce the issue.
      placeholder: |
        # Code here...
        print("Hello bug!")
    validations:
      required: false

  - type: input
    id: os
    attributes:
      label: OS
      placeholder: macOS
    validations:
      required: true
  - type: input
    id: language-version
    attributes:
      label: Python version
      placeholder: Python 3.0.0
    validations:
      required: true
  - type: input
    id: lib-version
    attributes:
      label: Application version
      placeholder: aichan 0.1.0
    validations:
      required: true

  - type: textarea
    id: additional-info
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
    validations:
      required: false
