name: Docs request
description: Suggest improvements or report issues with the documentation
labels: ['docs']
body:
  - type: checkboxes
    id: doc-type
    attributes:
      label: Please select one
      description: Choose **one** of the options below for your request.
      options:
        - label: Documentation improvement
        - label: Comments or docstring improvement

  - type: textarea
    id: doc-improvement
    attributes:
      label: Describe the documentation improvement
      description: A clear and concise description of what you'd like to improve or fix in the docs.
    validations:
      required: true

  - type: textarea
    id: doc-reference
    attributes:
      label: Where in the documentation?
      description: Specify the sections or parts of the docs that need updating. List them if possible.
      placeholder: |
        1. Section name or link
        2. Specific paragraph or code snippet
        3. Any other relevant detail
    validations:
      required: true

  - type: textarea
    id: additional-info
    attributes:
      label: Additional context
      description: Add any other context or references that might be useful (e.g., screenshots, related issues, or links).
    validations:
      required: false
