name: Feature request
description: Suggest an idea for this project
labels: ['feature-request']
body:
  - type: textarea
    id: feature
    attributes:
      label: Describe the feature or improvement you're requesting
      description: A clear and concise description of what you want to happen.
    validations:
      required: true

  - type: textarea
    id: why-needed
    attributes:
      label: Why is this needed?
      description: Explain the benefits this feature would bring.
    validations:
      required: true

  - type: textarea
    id: additional-info
    attributes:
      label: Additional context
      description: Add any other context or references that might be useful (e.g., screenshots, related issues, or links).
    validations:
      required: false
